parameters:
    bamiz_use_case.executor.class: Bamiz\UseCaseBundle\Execution\UseCaseExecutor
    bamiz_use_case.context_resolver.class: Bamiz\UseCaseBundle\Execution\UseCaseContextResolver
    bamiz_use_case.request_resolver.class: Bamiz\UseCaseBundle\UseCase\RequestResolver
    bamiz_use_case.container.use_case.class: Bamiz\UseCaseBundle\Container\DelegatingContainer
    bamiz_use_case.container.input_processor.class: Bamiz\UseCaseBundle\Container\Container
    bamiz_use_case.container.response_processor.class: Bamiz\UseCaseBundle\Container\Container

    bamiz_use_case.input_processor.form.class: Bamiz\UseCaseBundle\Processor\Input\FormInputProcessor
    bamiz_use_case.input_processor.http.class: Bamiz\UseCaseBundle\Processor\Input\HttpInputProcessor
    bamiz_use_case.input_processor.json_body.class: Bamiz\UseCaseBundle\Processor\Input\JsonInputProcessor

    bamiz_use_case.response_processor.twig.class: Bamiz\UseCaseBundle\Processor\Response\TwigRenderer
    bamiz_use_case.response_processor.json.class: Bamiz\UseCaseBundle\Processor\Response\JsonRenderer

    bamiz_use_case.default_context: default
    bamiz_use_case.contexts: []

services:

    ##################################
    # CORE SERVICES
    ##################################
    bamiz_use_case.executor:
        class: "%bamiz_use_case.executor.class%"
        arguments:
            - "@bamiz_use_case.container.use_case"
            - "@bamiz_use_case.context_resolver"

    bamiz_use_case.context_resolver:
        class: "%bamiz_use_case.context_resolver.class%"
        arguments: ["@bamiz_use_case.container.input_processor", "@bamiz_use_case.container.response_processor"]

    bamiz_use_case.container.use_case:
        class: "%bamiz_use_case.container.use_case.class%"
        arguments: ["@service_container"]

    bamiz_use_case.container.input_processor:
        class: "%bamiz_use_case.container.input_processor.class%"

    bamiz_use_case.container.response_processor:
        class: "%bamiz_use_case.container.response_processor.class%"

    bamiz_use_case.request_resolver:
        class: "%bamiz_use_case.request_resolver.class%"

    ##################################
    # INPUT PROCESSORS
    ##################################
    bamiz_use_case.input_processor.array:
        class: Bamiz\UseCaseBundle\Processor\Input\ArrayInputProcessor
        tags:
            - { name: use_case_input_processor, alias: array }

    bamiz_use_case.input_processor.composite:
        class: Bamiz\UseCaseBundle\Processor\Input\CompositeInputProcessor
        arguments: ["@bamiz_use_case.container.input_processor"]
        tags:
            - { name: use_case_input_processor, alias: composite }

    bamiz_use_case.input_processor.form:
        class: "%bamiz_use_case.input_processor.form.class%"
        arguments: ["@form.factory"]
        tags:
            - { name: use_case_input_processor, alias: form }

    bamiz_use_case.input_processor.http:
        class: "%bamiz_use_case.input_processor.http.class%"
        tags:
            - { name: use_case_input_processor, alias: http }

    bamiz_use_case.input_processor.json_body:
        class: "%bamiz_use_case.input_processor.json_body.class%"
        arguments: ["@serializer.encoder.json"]
        tags:
            - { name: use_case_input_processor, alias: json }

    ##################################
    # RESPONSE PROCESSORS
    ##################################
    bamiz_use_case.processor.response_processor.composite:
        class: Bamiz\UseCaseBundle\Processor\Response\CompositeResponseProcessor
        arguments: ["@bamiz_use_case.container.response_processor"]
        tags:
            - { name: use_case_response_processor, alias: composite }

    bamiz_use_case.processor.response_processor.identity:
        class: Bamiz\UseCaseBundle\Processor\Response\IdentityResponseProcessor
        tags:
            - { name: use_case_response_processor, alias: identity }

    bamiz_use_case.processor.response_processor.twig:
        class: "%bamiz_use_case.response_processor.twig.class%"
        arguments: ["@templating", "@form.factory"]
        tags:
            - { name: use_case_response_processor, alias: twig }

    bamiz_use_case.response_processor.json:
        class: "%bamiz_use_case.response_processor.json.class%"
        arguments: ["@serializer"]
        tags:
            - { name: use_case_response_processor, alias: json }
